"""Add status column to rag_instances

Revision ID: 4139d03d0c64
Revises: 96c76ec10f11
Create Date: 2025-11-12 00:37:07.320719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4139d03d0c64'
down_revision: Union[str, Sequence[str], None] = '96c76ec10f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_instances', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_instances', 'status')
    # ### end Alembic commands ###
